{
 "openapi": "3.0.2",
 "info": {
  "version": "1.0.0",
  "title": "Coverwallet OpenAPI",
  "x-logo": {
   "url": "https://www.coverwallet.com/assets/new-home/coverwallet_logo_negative-1ab94c362a7dcbf886eb51f48ff0d784cff7c5b45eeaa43a508bf359a02f2b29.svg",
   "backgroundColor": "#428ad8"
  },
  "description": "### Authentication\n\nAll endpoints - except the access token generation - require the\nAPI client to send a valid access token in the `Authorization` header.\nThis token is obtained using the [authentication endpoint](#/Authentication/get_access_token)\nand expires after 30 minutes. A new access token can be generated at any time,\nwhen the previous one has expired. Generating a new access token does not expire\nany existing token, so multiple valid access token can coexist.\n[...]"
 },
 "tags": [
  {
   "name": "Account",
   "description": "Operations about account"
  },
  {
   "name": "Policy",
   "description": "Operations about policy"
  },
  {
   "name": "Payment Transactions",
   "description": "Operations about payment transactions"
  },
  {
   "name": "Certificates",
   "description": "Operations about certificates"
  },
  {
   "name": "Invoices",
   "description": "Operations about invoices"
  },
  {
   "name": "Quote",
   "description": "Operations about quote"
  },
  {
   "name": "Endorsements",
   "description": "Changes about policy"
  },
  {
   "name": "Servicing",
   "description": "Operations about servicing"
  },
  {
   "name": "Catalog",
   "description": "Operations to request misc resources"
  },
  {
   "name": "Authentication",
   "description": "Operations to request access token"
  },
  {
   "name": "Subscriptions",
   "description": "Configuration of event subscriptions"
  },
  {
   "name": "Payment methods",
   "description": "Configuration of payment methods"
  },
  {
   "name": "Agent",
   "description": "Operations about agent"
  }
 ],
 "servers": [
  {
   "url": "https://public-api.aoncover.biz/v1"
  },
  {
   "url": "https://public-api.coveriq.info/v1"
  }
 ],
 "paths": {
  "/oauth/token": {
   "post": {
    "tags": [
     "Authentication"
    ],
    "summary": "Get an access token",
    "description": "Exchange your email and password by an access token that can be used to authenticate subsequent requests.",
    "operationId": "get_access_token"
   }
  },
  "/accounts": {
   "post": {
    "tags": [
     "Account"
    ],
    "summary": "Add a new account",
    "description": "Add a new account",
    "operationId": "add_account",
    "security": [
     {
      "oauth2": [
       "admin:account"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "Account"
    ],
    "summary": "Fetch an account",
    "description": "Fetch an account by external ID",
    "operationId": "list_account_by_external_id",
    "security": [
     {
      "oauth2": [
       "admin:account"
      ]
     }
    ]
   }
  },
  "/accounts/{id}": {
   "get": {
    "tags": [
     "Account"
    ],
    "summary": "Fetch an account",
    "description": "Fetch an existing account by ID.",
    "operationId": "get_account",
    "security": [
     {
      "oauth2": [
       "admin:account"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Account"
    ],
    "summary": "Update an account",
    "description": "Update an existing account. All fields are optional.",
    "operationId": "update_account",
    "security": [
     {
      "oauth2": [
       "admin:account"
      ]
     }
    ]
   }
  },
  "/accounts/{id}/contacts": {
   "post": {
    "deprecated": true,
    "tags": [
     "Account"
    ],
    "summary": "Add a contact. Deprecated in favor of \"POST /contacts\"",
    "description": "Add a contact",
    "operationId": "deprecated_add_contact",
    "security": [
     {
      "oauth2": [
       "admin:account"
      ]
     }
    ]
   }
  },
  "/accounts/{id}/policies": {
   "get": {
    "tags": [
     "Account"
    ],
    "summary": "Retrieve policies of an account",
    "description": "Retrieve policies of an account",
    "security": [
     {
      "oauth2": [
       "admin:policy"
      ]
     }
    ]
   }
  },
  "/accounts/{id}/servicing": {
   "post": {
    "tags": [
     "Account"
    ],
    "summary": "Set servicing data",
    "description": "# Servicing API\n\nThe use of this API is to change the servicing information of an account. This can include changing any of this data:\n\n* Account owner\n* Account advisor\n* Account segmentation fiels: segment, branch and business unit\n\nWhen the account is successfully updated a http 200 response code is returned\n\nIf either the account, the advisor or the owner are not found, a 404 http error code is returned and the detail of what has not been found is provided in th[...]",
    "operationId": "set_servicing",
    "security": [
     {
      "oauth2": [
       "admin:account"
      ]
     }
    ]
   }
  },
  "/policies": {
   "post": {
    "tags": [
     "Policy"
    ],
    "summary": "Add a new policy",
    "description": "This endpoints creates a new policy and returns the data of the policy created including the policy_id that needs to be used later for policy updates.\n\nThe external_id field should be unique\n",
    "operationId": "add_policy",
    "security": [
     {
      "oauth2": [
       "admin:policy"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "Policy"
    ],
    "summary": "Fetch policies filtered by query params",
    "description": "Fetch policies filtering by any of the supported parameters listed below. If no parameters are provided, no policies will be returned and a error will be triggered.",
    "operationId": "list_policies_by_filter",
    "security": [
     {
      "oauth2": [
       "admin:policy"
      ]
     }
    ]
   }
  },
  "/policies/{id}": {
   "get": {
    "tags": [
     "Policy"
    ],
    "summary": "Fetch a policy",
    "description": "Fetch an existing policy by ID.",
    "operationId": "get_policy",
    "security": [
     {
      "oauth2": [
       "admin:policy"
      ]
     }
    ]
   }
  },
  "/policies/{id}/endorsements": {
   "get": {
    "tags": [
     "Policy"
    ],
    "summary": "Retrieve endorsements of a policy",
    "description": "Retrieve endorsements of a policy",
    "security": [
     {
      "oauth2": [
       "admin:policy"
      ]
     }
    ]
   }
  },
  "/policies/{id}/payments": {
   "get": {
    "tags": [
     "Policy"
    ],
    "summary": "Fetch a list of policy payments",
    "description": "Fetch a list of policy payments",
    "operationId": "list_policy_payments",
    "security": [
     {
      "oauth2": [
       "admin:policy"
      ]
     }
    ]
   }
  },
  "/carriers": {
   "get": {
    "tags": [
     "Catalog"
    ],
    "summary": "Fetch carriers list",
    "description": "Fetch carriers list",
    "operationId": "list_carriers",
    "security": [
     {
      "oauth2": [
       []
      ]
     }
    ]
   }
  },
  "/insurance_types": {
   "get": {
    "tags": [
     "Catalog"
    ],
    "summary": "Fetch insurance types list",
    "description": "Fetch insurance types list",
    "operationId": "list_insurance_types",
    "security": [
     {
      "oauth2": [
       []
      ]
     }
    ]
   }
  },
  "/intermediaries": {
   "get": {
    "tags": [
     "Catalog"
    ],
    "summary": "Fetch intermediaries list",
    "description": "Fetch intermediaries list",
    "operationId": "list_intermediaries",
    "security": [
     {
      "oauth2": [
       []
      ]
     }
    ]
   }
  },
  "/subscriptions": {
   "post": {
    "tags": [
     "Subscriptions"
    ],
    "summary": "Add a new subscription",
    "description": "Add a new subscription",
    "operationId": "add_subscription",
    "security": [
     {
      "oauth2": [
       "admin:subscription"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "Subscriptions"
    ],
    "summary": "List all subscriptions",
    "description": "List all subscriptions",
    "operationId": "list_subscriptions",
    "security": [
     {
      "oauth2": [
       "admin:subscription"
      ]
     }
    ]
   }
  },
  "/subscriptions/{id}/rotate_key": {
   "put": {
    "tags": [
     "Subscriptions"
    ],
    "summary": "Rotate signing_key for subscription",
    "description": "Rotate signing_key for subscription",
    "operationId": "rotate_signing_key",
    "security": [
     {
      "oauth2": [
       "admin:subscription"
      ]
     }
    ]
   }
  },
  "/subscriptions/{id}": {
   "put": {
    "tags": [
     "Subscriptions"
    ],
    "summary": "Update subscription",
    "description": "Update subscription",
    "operationId": "update_subscription",
    "security": [
     {
      "oauth2": [
       "admin:subscription"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Subscriptions"
    ],
    "summary": "Delete subscription",
    "description": "Delete subscription",
    "operationId": "delete_subscription",
    "security": [
     {
      "oauth2": [
       "admin:subscription"
      ]
     }
    ]
   }
  },
  "/payment_methods": {
   "post": {
    "tags": [
     "Payment methods"
    ],
    "summary": "Add a new payment method",
    "description": "Add a new payment method",
    "operationId": "add_payment_method",
    "security": [
     {
      "oauth2": [
       "create:payment_method"
      ]
     }
    ]
   }
  },
  "/payments/{id}": {
   "get": {
    "tags": [
     "Payments"
    ],
    "summary": "Fetch a payment",
    "description": "Fetch a payment by ID",
    "operationId": "get_payment",
    "security": [
     {
      "oauth2": [
       "admin:payment"
      ]
     }
    ]
   }
  },
  "/payment_transactions/{id}": {
   "get": {
    "tags": [
     "Payment Transactions"
    ],
    "summary": "Fetch a payment transaction",
    "description": "Fetch a payment transaction by external (Stripe) ID",
    "operationId": "get_payment_transaction",
    "security": [
     {
      "oauth2": [
       "show:payment_transaction"
      ]
     }
    ]
   }
  },
  "/payment_transactions/{id}/refunds": {
   "post": {
    "tags": [
     "Payment Transactions"
    ],
    "summary": "Create a refund for a payment",
    "description": "To be requested by external clients to create a refund (full or partial) for a payment",
    "operationId": "create_refund",
    "security": [
     {
      "oauth2": [
       "admin:refund"
      ]
     }
    ]
   }
  },
  "/quotes/{id}": {
   "get": {
    "tags": [
     "Quote"
    ],
    "summary": "Fetch a quote",
    "description": "Fetch an existing quote by ID.",
    "operationId": "get_quote",
    "security": [
     {
      "oauth2": [
       "admin:quote"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Quote"
    ],
    "summary": "Partially update a quote",
    "description": "Partially update an existing quote.",
    "operationId": "patch_quote",
    "security": [
     {
      "oauth2": [
       "admin:quote"
      ]
     }
    ]
   }
  },
  "/quotes": {
   "get": {
    "tags": [
     "Quote"
    ],
    "summary": "Fetch list of quotes",
    "description": "Fetch quotes by external ID.",
    "operationId": "list_quotes",
    "security": [
     {
      "oauth2": [
       "admin:quote"
      ]
     }
    ]
   }
  },
  "/quotes/{id}/bind": {
   "post": {
    "tags": [
     "Quote"
    ],
    "summary": "Sync a quote",
    "description": "Sync a quote purchased outside of CW",
    "operationId": "update_quote",
    "security": [
     {
      "oauth2": [
       "admin:quote"
      ]
     }
    ]
   }
  },
  "/endorsements": {
   "post": {
    "tags": [
     "Endorsements"
    ],
    "summary": "Create an endorsement or change in the policy",
    "description": "Create an endorsement or change in the policy",
    "operationId": "create_policy_endorsement",
    "security": [
     {
      "oauth2": [
       "admin:policy"
      ]
     }
    ]
   }
  },
  "/endorsements/{id}": {
   "get": {
    "tags": [
     "Endorsements"
    ],
    "summary": "Fetch an endorsement",
    "description": "Fetch an endorsement by ID",
    "operationId": "get_endorsement",
    "security": [
     {
      "oauth2": [
       "admin:policy"
      ]
     }
    ]
   }
  },
  "/endorsements/{id}/commissions": {
   "get": {
    "tags": [
     "Comissions"
    ],
    "summary": "Fetch the commissions applied over an endorsement",
    "description": "Fetch the commissions by endorsement ID",
    "operationId": "get_endorsement_commissions",
    "security": [
     {
      "oauth2": [
       "admin:policy"
      ]
     }
    ]
   }
  },
  "/endorsements/{id}/payments": {
   "get": {
    "tags": [
     "Endorsements"
    ],
    "summary": "Fetch a list of endorsement payments",
    "description": "Fetch a list of endorsement payments",
    "operationId": "list_endorsement_payments",
    "security": [
     {
      "oauth2": [
       "admin:policy"
      ]
     }
    ]
   }
  },
  "/contacts": {
   "post": {
    "tags": [
     "Contact"
    ],
    "summary": "Add a contact",
    "description": "Add a contact",
    "operationId": "add_contact",
    "security": [
     {
      "oauth2": [
       "admin:account"
      ]
     }
    ]
   }
  },
  "/contacts/{id}": {
   "patch": {
    "tags": [
     "Contact"
    ],
    "summary": "Update a contact",
    "description": "Update a contact of an account. All fields except \"contact_id\" and \"account_id\" are optional.",
    "operationId": "update_contact",
    "security": [
     {
      "oauth2": [
       "admin:account"
      ]
     }
    ]
   }
  },
  "/accounts/{id}/certificates": {
   "post": {
    "deprecated": true,
    "tags": [
     "Account",
     "Certificates"
    ],
    "summary": "Create a new certificate",
    "description": "Create a new certificate",
    "operationId": "add_account_document_certificate",
    "security": [
     {
      "oauth2": [
       "admin:certificate"
      ]
     }
    ]
   }
  },
  "/accounts/{id}/invoices": {
   "post": {
    "tags": [
     "Account",
     "Invoices"
    ],
    "summary": "Create a new invoice",
    "description": "Create a new invoice",
    "operationId": "add_account_document_invoice",
    "security": [
     {
      "oauth2": [
       "admin:invoice"
      ]
     }
    ]
   }
  },
  "/servicing/accounts/{id}/account_changes": {
   "post": {
    "tags": [
     "Servicing"
    ],
    "summary": "Apply account changes to an existing policy",
    "description": "Apply account changes to an existing policy",
    "operationId": "apply_account_changes",
    "security": [
     {
      "oauth2": [
       "admin:account"
      ]
     }
    ]
   }
  },
  "/servicing/policies/{id}/midterm_changes": {
   "post": {
    "tags": [
     "Servicing"
    ],
    "summary": "Apply midterm changes to an existing policy",
    "description": "Apply midterm changes to an existing policy",
    "operationId": "apply_midterm_changes",
    "security": [
     {
      "oauth2": [
       "admin:endorsement"
      ]
     }
    ]
   }
  },
  "/servicing/policies/{id}/cancellation": {
   "post": {
    "tags": [
     "Servicing"
    ],
    "summary": "Apply cancellation to an existing policy",
    "description": "Apply cancellation to an existing policy",
    "operationId": "apply_cancellation",
    "security": [
     {
      "oauth2": [
       "admin:endorsement"
      ]
     }
    ]
   }
  },
  "/servicing/policies/{id}/reinstatement": {
   "post": {
    "tags": [
     "Servicing"
    ],
    "summary": "Apply reinstatement to an existing policy",
    "description": "Apply reinstatement to an existing policy",
    "operationId": "apply_reinstatement",
    "security": [
     {
      "oauth2": [
       "admin:endorsement"
      ]
     }
    ]
   }
  },
  "/requests": {
   "post": {
    "tags": [
     "Agent request"
    ],
    "summary": "Create agent request",
    "description": "Create agent request",
    "operationId": "create_request",
    "security": [
     {
      "oauth2": [
       "admin:account"
      ]
     }
    ]
   }
  },
  "/agents/sync": {
   "post": {
    "deprecated": true,
    "tags": [
     "Agent"
    ],
    "summary": "Create or update agent",
    "description": "Create or update agent",
    "operationId": "sync_agent",
    "security": [
     {
      "oauth2": [
       "admin:agent"
      ]
     }
    ]
   }
  },
  "/applications": {
   "post": {
    "tags": [
     "Application"
    ],
    "summary": "Create a new application",
    "description": "Add a new application",
    "operationId": "add_application_request",
    "security": [
     {
      "oauth2": [
       "admin:application_request"
      ]
     }
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "oauth2": {
    "type": "oauth2",
    "flows": {
     "clientCredentials": {
      "tokenUrl": "https://public-api.aoncover.biz/v1/oauth/token",
      "scopes": {
       "admin:account": "Grants full access to read, create and update accounts",
       "create:refund": "Grants to create refunds",
       "show:payment_transaction": "Grants access to retrieve a payment transaction",
       "admin:policy": "Grants full access to read, create and update policies",
       "admin:subscription": "Grants access to manage subscriptions to events",
       "admin:quote": "Grants access to read and update quotes",
       "create:payment_method": "Grants access to create payment methods of an accounts",
       "admin:application": "Grants full access to read, create and update applications"
      }
     }
    }
   }
  }
 }
}